In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import warnings

In [2]:
data=pd.read_csv(r'D:\AI\ai_deploma_master\ai_deploma_master\files\PlayTennis 1.csv')

In [3]:
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [4]:
data.columns
data.columns[0]

'Outlook'

In [5]:
from sklearn.preprocessing import OrdinalEncoder
for i in data.columns:
    encoder = OrdinalEncoder()
    data[i] = encoder.fit_transform(data[[i]])

In [6]:
outlook_encoder=OrdinalEncoder()
data['Outlook']=outlook_encoder.fit_transform(data[['Outlook']])

In [7]:
temp_encoder=OrdinalEncoder()
data['Temperature']=temp_encoder.fit_transform(data[['Temperature']])

In [8]:
Hum_encoder=OrdinalEncoder()
data['Humidity']=Hum_encoder.fit_transform(data[['Humidity']])

In [9]:
Wind_encoder=OrdinalEncoder()
data['Wind']=Wind_encoder.fit_transform(data[['Wind']])

In [10]:
Play_Tennis_encoder=OrdinalEncoder()
data['Play Tennis']=Play_Tennis_encoder.fit_transform(data[['Play Tennis']])

In [11]:
data

    Outlook  Temperature  Humidity  Wind  Play Tennis
0       2.0          1.0       0.0   1.0          0.0
1       2.0          1.0       0.0   0.0          0.0
2       0.0          1.0       0.0   1.0          1.0
3       1.0          2.0       0.0   1.0          1.0
4       1.0          0.0       1.0   1.0          1.0
5       1.0          0.0       1.0   0.0          0.0
6       0.0          0.0       1.0   0.0          1.0
7       2.0          2.0       0.0   1.0          0.0
8       2.0          0.0       1.0   1.0          1.0
9       1.0          2.0       1.0   1.0          1.0
10      2.0          2.0       1.0   0.0          1.0
11      0.0          2.0       0.0   0.0          1.0
12      0.0          1.0       1.0   1.0          1.0
13      1.0          2.0       0.0   0.0          0.0

In [12]:
x=data.drop(['Play Tennis'],axis=1)
y=data['Play Tennis']

In [13]:
x_train , x_test , y_train , y_test = train_test_split(x,y,train_size=0.8,random_state = 10)

In [14]:
clf=DecisionTreeClassifier(criterion='gini')
clf.fit(x_train, y_train)
y_pred=clf.predict( x_test )

In [15]:
clf_1=DecisionTreeClassifier(criterion='entropy')
clf_1.fit(x_train, y_train)
y_pred_1=clf.predict( x_test )

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print("accuracy with gini",accuracy_score(y_test,y_pred))
print('--------------------------------------------------')
print("accuracy with entorpy",accuracy_score(y_test,y_pred_1))
print('--------------------------------------------------')
print("classification_report",classification_report(y_test,y_pred))
print('--------------------------------------------------')
print("classification_report",classification_report(y_test,y_pred_1))

accuracy with gini 0.6666666666666666
--------------------------------------------------
accuracy with entorpy 0.6666666666666666
--------------------------------------------------
classification_report               precision    recall  f1-score   support

         0.0       0.50      1.00      0.67         1
         1.0       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

--------------------------------------------------
classification_report               precision    recall  f1-score   support

         0.0       0.50      1.00      0.67         1
         1.0       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

In [25]:
from sklearn import tree
plt.figure(figsize=(12,8))
tree.plot_tree(clf,filled=True,feature_names=x.columns,class_names=play_encoder.categories_[0],rounded=True)
plt.show()

NameError: name 'play_encoder' is not defined

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'